Repository alchemy-run/alchemy, pull requests merged in 2025-08, with the labels that each got.

#483 chore: dynamic OG generation
  .github/workflows/publish.yml
  alchemy-web/alchemy.run.ts
  alchemy-web/astro.config.mjs
  alchemy-web/package.json
  alchemy-web/src/pages/og/[...route].png.ts
  alchemy-web/src/routeData.ts
  bun.lock
Labels: documentation

#827 fix(cloudflare): correct wrangler.json assets config
  alchemy/src/cloudflare/wrangler.json.ts
Labels: bug

#835 fix(cloudflare): propagate compatibility preset to wrangler.jsonc
  alchemy/src/cloudflare/website.ts
Labels: bug

#847 fix(cloudflare): use glob instead of fs.glob for node 20 compatibility
  alchemy/src/cloudflare/d1-migrations.ts
  alchemy/src/cloudflare/worker-bundle.ts
Labels: bug

#855 fix(cli): ensure exit code 0 for sigint
  alchemy/bin/services/execute-alchemy.ts
Labels: bug

#853 fix(cloudflare): register durable object bindings for websites
  alchemy/src/cloudflare/miniflare/build-worker-options.ts
  alchemy/src/cloudflare/miniflare/miniflare-controller.ts
Labels: bug

#901 feat(cloudflare): r2 bucket lifecycle and lock rules
  alchemy-web/src/content/docs/providers/cloudflare/bucket.md
  alchemy/src/cloudflare/bucket.ts
  alchemy/test/cloudflare/bucket.test.ts
  bun.lock
  package.json
  vitest.setup.ts
Labels: enhancement

#892 fix(cloudflare): skip path validation during astro output type check
  alchemy/src/cloudflare/astro/astro.ts
  alchemy/src/cloudflare/miniflare/paths.ts
Labels: bug

#903 fix(cloudflare): set `spa: false` for astro resource
  alchemy-web/public/robots.txt
  alchemy/src/cloudflare/astro/astro.ts
  bun.lock
Labels: bug

#916 fix(cloudflare): sync node compat plugin with workers-sdk
  alchemy/package.json
  alchemy/src/cloudflare/bundle/externals.ts
  alchemy/src/cloudflare/bundle/nodejs-builtin-modules.ts
  alchemy/src/cloudflare/bundle/plugin-als-external.ts
  alchemy/src/cloudflare/bundle/plugin-compat-warning.ts
  alchemy/src/cloudflare/bundle/plugin-hybrid-node-compat.ts
  alchemy/src/cloudflare/bundle/plugin-node-compat.ts
  alchemy/src/cloudflare/worker-bundle.ts
  alchemy/test/cloudflare/bundle.test.ts
  alchemy/test/cloudflare/test-handlers/workos.ts
  bun.lock
Labels: bug

#923 feat(cloudflare): adopt hyperdrive
  alchemy/src/cloudflare/hyperdrive.ts
  alchemy/test/cloudflare/hyperdrive.test.ts
Labels: enhancement
